import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "primereact/resources/themes/lara-light-blue/theme.css";
import "primereact/resources/primereact.min.css";
import 'primeicons/primeicons.css';
import "./globals.css";

export const metadata: Metadata = {
  title: "NextJS CRUD App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-3xl mx-auto p-4">
          <Navbar></Navbar>
          <div className="mt-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
